### ISSUE TITLE
Questions about datasets and augmentations.

### ISSUE THREAD

**Issue by zhulf0804** [ldkong1205/PointCloud-C#3]
Hello ldkong1205:

Thanks for the PointCloud-C Benchmark and Challenge for point cloud analysis.

I have two questions for the Challenge on the Codalab, mainly about datasets and augmentations.

1. Is the full PointCloud-C dataset (downloaded from https://pointcloud-c.github.io/download.html) allowed for model training ?

2. "Corruptions that are part of ModelNet-C and ShapeNet-C are strictly NOT allowed to be included as training augmentations" means we can't use the 7 augmentations (listed at https://pointcloud-c.github.io/details.html) during training ? However, some augmentations, such as jitter and scale, are widely used training tricks in previous works.

Looking forward to your reply.

**Comment by jiawei-ren** [comment]
Thanks for your interest in the challenge!

> Is the full PointCloud-C dataset (downloaded from https://pointcloud-c.github.io/download.html) allowed for model training ?

No, it is not allowed to be used for training. It can be used as a validation set. We will add an announcement on the CodaLab page.

> "Corruptions that are part of ModelNet-C and ShapeNet-C are strictly NOT allowed to be included as training augmentations" means we can't use the 7 augmentations (listed at https://pointcloud-c.github.io/details.html) during training? However, some augmentations, such as jitter and scale, are widely used training tricks in previous works.

For conventional augmentations including _jittering_, _scaling_, _translation_, and _rotation_, please follow the DGCNN Protocol [1], i.e., only 

1.   random anisotropic scaling in the range [2/3, 3/2] and
2.   random translation in the range [-0.2, +0.2]

are allowed. All other conventional augmentations are not allowed. Any Other augmentations that are similar to the 7 atomic corruptions are also not allowed. We will specify it on the CodaLab page.

[1] Goyal et. al., Revisiting Point Cloud Shape Classification with a Simple and Effective Baseline, ICML 2021

For your reference:

- Evaluation Protocol in our [ModelNet-C paper](https://arxiv.org/pdf/2202.03377.pdf):

<img width="595" alt="Screenshot 2022-07-26 at 5 25 45 PM" src="https://user-images.githubusercontent.com/72253125/180973036-6eec4e1e-dcef-45a9-b9c1-3471cc813bc7.png">


- DGCNN Protocol in [Goyal et. al](https://arxiv.org/pdf/2106.05304.pdf):

<img width="854" alt="Screenshot 2022-07-26 at 5 23 12 PM" src="https://user-images.githubusercontent.com/72253125/180972520-c3b82155-56df-4446-8de0-1506f962ec11.png">

**Comment by zhulf0804** [comment]
I understand now.

Thanks for your patient reply.
