### ISSUE TITLE
about git+git://github.com/imankgoyal/etw_pytorch_utils.git@v1.1.1#egg=etw_pytorch_utils

### ISSUE THREAD

**Issue by Roywangj** [ldkong1205/PointCloud-C#4]
hi, thanks for your work. My server cant connect to github, so i cant download this on shell. Besides, i have never seen command like 'git+git:', so i dont know how to find alternative ways. Would you be kind to tell me alternative ways?

Thanks!

**Comment by ldkong1205** [comment]
Hi @Roywangj, thanks for reaching us!

For your question, could you describe more details on how you encounter errors for downloading the mentioned repository?

**Comment by Roywangj** [comment]
My server can't reach github, so i can't perform 'git+git://github.com/imankgoyal/etw_pytorch_utils.git@v1.1.1#egg=etw_pytorch_utils' (L1 in https://github.com/ldkong1205/PointCloud-C/blob/main/requirements.txt)

**Comment by ldkong1205** [comment]
Hi @Roywangj, thank you for providing the information.

For your question, please download directly the ``etw_pytorch_utils`` package from https://github.com/imankgoyal/etw_pytorch_utils, unzip it, and rename it from ``etw_pytorch_utils-master`` to ``etw_pytorch_utils``.

Next, ``activate`` your conda environment; go to (``cd`` to) ``/etw_pytorch_utils`` and use the following command:
```
pip install .
```

The package should now be installed in the environment. Please let us know if you have any other questions.

**Comment by Roywangj** [comment]
Thanks for your kindness. About this i have an extra question, its not a cuda op and i can't find  'setup.py' file. So what the `pip install .` command do? Does it complie some cuda extensions or do some other functions?

**Comment by ldkong1205** [comment]
Hi @Roywangj, we have tested the above procedures. No``setup.py`` needed as we are not using ``pip install -e xxx``. Could you please try again by following the exact same steps? Do let us know whether or not this works for you.

**Comment by Roywangj** [comment]
Hi @ldkong1205 , i have tried by steps but failed. Here is the error:
`Successfully built etw-pytorch-utils statistics visdom torchfile
Installing collected packages: torchfile, websocket-client, tqdm, tornado, scipy, pyzmq, jsonpointer, docutils, statistics, jsonpatch, visdom, etw-pytorch-utils
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pointnet2 2.1.1 requires etw_pytorch_utils==1.1.1, but you have etw-pytorch-utils 1.1.2 which is incompatible.
Successfully installed docutils-0.19 etw-pytorch-utils-1.1.2 jsonpatch-1.32 jsonpointer-2.3 pyzmq-23.2.0 scipy-1.9.0 statistics-1.0.3.5 torchfile-0.1.0 tornado-6.2 tqdm-4.64.0 visdom-0.1.8.9 websocket-client-1.3.3
`
Now i want to turn the ` __version__ = "1.1.2"` in https://github.com/imankgoyal/etw_pytorch_utils/blob/master/etw_pytorch_utils/__init__.py to ` __version__ = "1.1.1"`, but i dont know how to delete the wrong compilled files before recompiling, such like `rm -rf /build` if using `python setup.py develop`

**Comment by ldkong1205** [comment]
Hi @Roywangj, thanks for your update!

To uninstall it, activate your conda environment first and use the following command:
```
pip uninstall etw-pytorch-utils
``` 

Then prompt ``y`` as follows:
```
Proceed (Y/n)? y
Successfully uninstalled etw-pytorch-utils-1.1.2
```

You should now be able to reinstall it with the modified version.

**Comment by Roywangj** [comment]
Hi @ldkong1205 , thanks for your advice.

**Comment by ldkong1205** [comment]
Closing this issue now. Feel free to re-open it if you encounter any other problems.
