### ISSUE TITLE
about the code of WOLFMix

### ISSUE THREAD

**Issue by Roywangj** [ldkong1205/PointCloud-C#6]
Hi @jiawei-ren , i have searched the whole file for codes of  WOLFMix  but failed, i only found the codes of RSMix and PointWOLF. Would you please release the code of WOLFMix and update corresponding training codes,  i think this will be great value to helping understanding the workflow.

**Comment by Roywangj** [comment]
> For the deformation step, we use the default hyper-parameters in PointWOLF (Kim et al., 2021). We set the number of anchors to 4, sampling method to farthest point sampling, kernel bandwidth to 0.5, maximum local rotation range to 10 degrees, maximum local scaling to 3, and maximum local translation to 0.25. AugTune proposed along with PointWOLF is not used in training. For the mixing step, we use the default hyper-parameters in RSMix (Lee et al., 2021). We set RSMix probability to 0.5, β to 1.0, and the maximum number of point modifications to 512. For training, the number of neighbors in k-NN is reduced to 20 and the number of epochs is increased to 500 for all methods.

Even details are provided on paper, it's still confused to follow WOLFMix.

Thanks

**Comment by jiawei-ren** [comment]
The [GDANet sub-directroy](https://github.com/jiawei-ren/ModelNet-C/tree/main/GDANet) includes the implementation of WOLFMix. 

To train GDANet+ WOLFMix, please use the following command:
`python main_cls.py --epochs 500 --beta 1.0 --rdscale --shift --pw`

**Comment by Roywangj** [comment]
hi @jiawei-ren ， i have added PointWOLF to my method. However,  i want to reproduce WOLFMix but failed.  I want to know more details about it, would you release the codes of WOLFMix ?

**Comment by jiawei-ren** [comment]
The "PointWOLF" should be "WOLFMix" in the previous comment. Sorry for the typo.

**Comment by Roywangj** [comment]
hi, @jiawei-ren. Fine, thanks for your patient relpy.
