### ISSUE TITLE
Question about the ShapeNet-C paper.

### ISSUE THREAD

**Issue by dlsrbgg33** [ldkong1205/PointCloud-C#8]
Hi, Thank you for the great work.

While I am using your Dataset (ModelNet-C and ShapeNet-C), I cannot find the related paper for ShapeNet-C (arxiv 22).
Could you share it so that I can cite the paper?

Thanks

**Comment by ldkong1205** [comment]
Hi @dlsrbgg33, thank you so much for your interest in this work! We are so sorry that the new version of this work which includes both Model-C and ShapeNet-C is still under preparation. We might need a few more weeks to finish the writing. We will finish it ASAP and let you know once the preprint is ready. Thanks a lot!

**Comment by dlsrbgg33** [comment]
Thank you!
